language: java
services:
  - mysql 
  - postgresql
  - redis-server

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'CREATE DATABASE test;' -U postgres
  - wget http://www.us.apache.org/dist/kafka/0.8.2.1/kafka_2.10-0.8.2.1.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
  - sleep 5
  - bin/kafka-topics.sh --list --bootstrap-server localhost:9092

sudo: false

before_script:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)

