language: java
services:
  - mysql 
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'

before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres

sudo: false

before_script:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)

