/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dbtest;

import org.junit.Test;

import redis.clients.jedis.Jedis;

import static org.junit.Assert.*;

import java.sql.SQLException;

public class DBTest {
	@Test
	public void testMySQL() throws SQLException {
		DB db = new DB();
		assertTrue("Able to connect to MySQL instance",
				db.connect("jdbc:mysql://localhost/test", "com.mysql.cj.jdbc.Driver", "travis", ""));
		db.close();
	}

	@Test
	public void testPostgresql() throws SQLException {
		DB db = new DB();
		assertTrue("Able to connect to Postgresql instance",
				db.connect("jdbc:postgresql://localhost:5432/test", "org.postgresql.Driver", "postgres", ""));
		db.close();
	}

	@Test
	public void testRedis() {
		Jedis jedis = new Jedis("localhost");
		System.out.println(jedis.info());
		assertTrue(jedis.ping().toLowerCase().contains("pong"));
		jedis.close();
	}
}
