/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dbtest;

import org.junit.Test;

import redis.clients.jedis.Jedis;

import static org.junit.Assert.*;

import java.sql.SQLException;

public class DBTest {
	@Test
	public void testMySQL() throws SQLException {
		DB db = new DB();
		assertTrue("Able to connect to MySQL instance",
				db.connect(DB.getEnv("MYSQL_URL", "jdbc:mysql://localhost/test"), "com.mysql.cj.jdbc.Driver",
						DB.getEnv("MYSQL_USER", "travis"), DB.getEnv("MYSQL_PASS", "")));
		db.close();
	}

	@Test
	public void testPostgresql() throws SQLException {
		DB db = new DB();
		assertTrue("Able to connect to Postgresql instance",
				db.connect(DB.getEnv("PG_URL", "jdbc:postgresql://localhost:5432/testt"), "org.postgresql.Driver",
						DB.getEnv("PG_USER", "postgres"), DB.getEnv("PG_PASS", "")));
		db.close();
	}

	@Test
	public void testRedis() {
		Jedis jedis = new Jedis("localhost");
		System.out.println(jedis.info());
		assertTrue("Able to connect to Redis server", jedis.ping().toLowerCase().contains("pong"));
		jedis.close();
	}
}
