/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dbtest;

import org.junit.Test;
import static org.junit.Assert.*;

import java.sql.SQLException;

public class DBTest {
	@Test
	public void testMySQL() throws SQLException {
		DB db = new DB();
		assertTrue("Able to connect to MySQL instance",
				db.connect("jdbc:mysql://localhost/travis", "com.mysql.cj.jdbc.Driver", "travis", ""));
		db.close();
	}

	@Test
	public void testPostgresql() throws SQLException {
		DB db = new DB();
		assertTrue("Able to connect to Postgresql instance",
				db.connect("jdbc:postgresql://localhost:5432/travis", "org.postgresql.Driver", "postgres", "test"));
		db.close();
	}
}
